### ISSUE TITLE
Center sketchBoard in Middle of Page

### ISSUE THREAD

**Issue by Zhongy1** [yhu4592/etch-a-sketch#1]
Sometimes, your project will have one main focus, and you may want to center it. If you do want to do that, here's how.

Add the following to your stylesheet:
```css
body {
    width: 100%;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
}
```

![Screen Shot 2020-08-05 at 8 37 51 PM](https://user-images.githubusercontent.com/34720343/89481350-26bbe580-d75d-11ea-975d-4b434e530759.png)

The flex display property works if the element has a defined width/height. You can notice that the width is set to 100% and height is set to 100vh, which is 100% of the current viewport height.

If you want to learn more about flex, here's a great tool to learn it: https://flexboxfroggy.com/
